name: Compile Latex and Release PDF  

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: mark_read_cv.tex
          
      # The following upload and download are not really required. 
      # The git add and push commands that follow are what places the PDF file
      # in the repository. 
#       - name: Upload PDF file
#         uses: actions/upload-artifact@v3
#         with:
#           name: BUILT_PDF
#           path: mark_read_cv.pdf

#       - name: Download PDF file
#         uses: actions/download-artifact@v3
#         with:
#           name: BUILT_PDF
#           path: dist/mark_read_cv.pdf
          
      - name: Configure Git
        run: |
          git config --global user.name "marknormanread"
          git config --global user.email "mark.norman.read@gmail.com"

      - name: Add file
        run: |
          git add mark_read_cv.pdf 
          git add mark_read_cv.log

      - name: Commit changes
        run: |
          git commit -m "Add generated file"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
